# Generated by Django 4.1.3 on 2022-11-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_vagas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nicho_mercado',
            field=models.CharField(choices=[('M', 'Marketing'), ('N', 'Nutrição'), ('D', 'Design'), ('T', 'Tecnologia'), ('SP', 'Setor Publico'), ('AM', 'Agencia de Modelo')], max_length=3),
        ),
    ]
